package com.greenerpastures.arcade;

import java.util.List;

/**
 * GENERATED by gen_crowd.py (scratchpad/pmd) - species with verified fan-made Walk sheets bundled
 * in the UI (23 of them). The sprint-clicker's target MUST come from this list or the client
 * has nothing to animate; crowdsprites.js is generated from the same data - regenerate together.
 */
public final class CrowdPool {
    private CrowdPool() {}

    public static final List<String> POOL = List.of("chewtle", "dedenne", "deerling", "dreepy", "emolga", "fidough", "goomy", "hatenna", "lechonk", "litten", "milcery", "mimikyu", "minccino", "morpeko", "nickit", "pawmi", "rockruff", "sinistea", "skwovet", "snom", "wooloo", "yamper", "zorua");
}
