package com.greenerpastures.arcade;

import java.util.List;

/**
 * GENERATED by gen_carddeck.py (scratchpad/pmd) - the TOP DECK species pool. Every name has a
 * verified FAN-MADE portrait bundled in the UI (66 species; artists in CREDITS-PMD.md and the
 * jar's pmd_credits.txt). The client's carddeck.js is generated from the SAME list - the two must
 * never drift, so regenerate both together.
 */
public final class TopDeckPool {
    private TopDeckPool() {}

    public static final List<String> POOL = List.of(
            "applin",
            "arrokuda",
            "axew",
            "blitzle",
            "bounsweet",
            "capsakid",
            "chespin",
            "chewtle",
            "clobbopus",
            "cramorant",
            "cufant",
            "cutiefly",
            "dedenne",
            "deerling",
            "dreepy",
            "eldegoss",
            "emolga",
            "falinks",
            "fennekin",
            "fidough",
            "flittle",
            "froakie",
            "fuecoco",
            "goomy",
            "gossifleur",
            "greavard",
            "grookey",
            "hatenna",
            "impidimp",
            "lechonk",
            "litten",
            "milcery",
            "mimikyu",
            "minccino",
            "morpeko",
            "nacli",
            "nickit",
            "oshawott",
            "pancham",
            "pawmi",
            "petilil",
            "pincurchin",
            "popplio",
            "quaxly",
            "rockruff",
            "rowlet",
            "scorbunny",
            "shroodle",
            "silicobra",
            "sinistea",
            "sizzlipede",
            "skwovet",
            "smoliv",
            "snivy",
            "snom",
            "sobble",
            "sprigatito",
            "tadbulb",
            "tandemaus",
            "tepig",
            "togedemaru",
            "toxel",
            "wattrel",
            "wooloo",
            "yamper",
            "zorua");
}
