package com.greenerpastures.arcade;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * GENERATED by gen_carddeck2.py (scratchpad/pmd) - the TOP DECK species catalog: every species'
 * verified FAN-MADE emotion portraits (66 species; 51 with >= 3 emotions are deal-eligible,
 * the thin rest appear only as strangers). The client's carddeck.js is generated from the SAME
 * data - regenerate both together, never edit by hand.
 */
public final class TopDeckPool {
    private TopDeckPool() {}

    public static final Map<String, List<String>> EMOTIONS;
    static {
        Map<String, List<String>> m = new LinkedHashMap<>();
        m.put("applin", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("arrokuda", List.of("normal"));
        m.put("axew", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("blitzle", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("bounsweet", List.of("angry", "determined", "happy", "inspired", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("capsakid", List.of("normal"));
        m.put("chespin", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("chewtle", List.of("normal"));
        m.put("clobbopus", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("cramorant", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("cufant", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("cutiefly", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("dedenne", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("deerling", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("dreepy", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("eldegoss", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("emolga", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("falinks", List.of("normal"));
        m.put("fennekin", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("fidough", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("flittle", List.of("normal"));
        m.put("froakie", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("fuecoco", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("goomy", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("gossifleur", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("greavard", List.of("happy", "normal", "sad"));
        m.put("grookey", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("hatenna", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("impidimp", List.of("normal"));
        m.put("lechonk", List.of("happy", "normal"));
        m.put("litten", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("milcery", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("mimikyu", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("minccino", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("morpeko", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("nacli", List.of("normal"));
        m.put("nickit", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("oshawott", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("pancham", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("pawmi", List.of("angry", "determined", "happy", "inspired", "normal", "shouting", "sigh", "teary_eyed", "worried"));
        m.put("petilil", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("pincurchin", List.of("normal"));
        m.put("popplio", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("quaxly", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("rockruff", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("rowlet", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("scorbunny", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("shroodle", List.of("normal"));
        m.put("silicobra", List.of("happy", "normal", "sad", "teary_eyed"));
        m.put("sinistea", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("sizzlipede", List.of("joyous", "normal"));
        m.put("skwovet", List.of("normal"));
        m.put("smoliv", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("snivy", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("snom", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("sobble", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("sprigatito", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("tadbulb", List.of("normal"));
        m.put("tandemaus", List.of("normal"));
        m.put("tepig", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("togedemaru", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("toxel", List.of("normal"));
        m.put("wattrel", List.of("happy", "inspired", "normal", "pain"));
        m.put("wooloo", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("yamper", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        m.put("zorua", List.of("angry", "crying", "happy", "joyous", "normal", "pain", "sad", "sigh", "surprised", "worried"));
        EMOTIONS = Collections.unmodifiableMap(m);
    }

    public static final List<String> POOL = List.copyOf(EMOTIONS.keySet());
}
